import Head from 'next/head'
import { Inter } from '@next/font/google'
import { useState } from 'react'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

interface BookProps {

}

export default function Home() {
  
  const [query, setQuery] = useState('');
  const [books, setBooks] = useState<any>([]);

  const handleSearch = async () => {
    try {
      const response = await axios.get(`https://www.googleapis.com/books/v1/volumes?q=${query}`);
      setBooks(response.data.items);
    } catch (err) {
      console.log(err);
    }
  };


  return (
    <>
    
    <Head>
        <title>The Seeker</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
    <main>
      <input type="text" placeholder="Search books..." value={query} onChange={(e) => setQuery(e.target.value)} />
      <button onClick={handleSearch}>Search</button>
      <ul>
        {books.map((book: any) => (
          <li key={book.id}>{book.volumeInfo.title}</li>
        ))}
      </ul>
    </main>
    </>
  );
}
